### ISSUE TITLE
Unicode vs. str issue on 'Save file' (using the GUI) 

### ISSUE THREAD

**Issue by rafwiewiora** [openmm/pdbfixer#136]
On pressing 'Save file' in the GUI, server crashes with exception:

```
Exception happened during processing of request from ('127.0.0.1', 62352)
Traceback (most recent call last):
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/pdbfixer/uiserver.py", line 29, in do_POST
    self.invokeCallback(parameters)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/pdbfixer/uiserver.py", line 41, in invokeCallback
    callback[path](parameters, self)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/pdbfixer/ui.py", line 139, in saveFilePageCallback
    output.write("REMARK   1 PDBFIXER FROM: %s\n" % fixer.source)
TypeError: unicode argument expected, got 'str'
```

Confused why this is happening, looking at the code it does a:

``` python
from cStringIO import StringIO
output = StringIO
output.write(...)
```

and that should be working with the `str`...

**Comment by rafwiewiora** [comment]
Unless somehow it's not doing `from cStringIO import StringIO` but `from io import StringIO`, that would give this exception - not sure how the python version check (I see that was changed in https://github.com/pandegroup/pdbfixer/commit/1bec1b7c941b9244275dfe4f8b3431e7c1ebdb7c ) would be failing though.

**Comment by peastman** [comment]
Are you sure your code is up to date?  That looks like the sort of error I was getting before I fixed it last month.

**Comment by jchodera** [comment]
Did we cut a new release for that bugfix?

**Comment by peastman** [comment]
Not yet.  It was just fixed last month.

**Comment by jchodera** [comment]
That probably explains why the conda version @rafwiewiora was using doesn't have the bugfix, though.  :)

How about cutting a bugfix release and I can bump the conda package version?

Should I also update the minimum openmm version to 7.0.1 since we currently pin to at least 7.0rc1, or is it fine as is?

**Comment by rafwiewiora** [comment]
Oh yeah I was just conda installing!

**Comment by peastman** [comment]
I just created a 1.3.1 release.  The required OpenMM version hasn't changed, although perhaps it would be good to update that anyway as another way of encouraging people to upgrade?

**Comment by jchodera** [comment]
Updated recipe: https://github.com/omnia-md/conda-recipes/pull/560
